## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('wifi-simple-adhoc-60ghz-tcp', ['core', 'simulator', 'mobility', 'wifi'])
    obj.source = 'wifi-simple-adhoc-60ghz-tcp.cc'
